apiVersion: apps/v1
kind: Deployment
metadata:
  name: CHANGEME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CHANGEME
  template:
    metadata:
      labels:
        app: CHANGEME
    spec:
      containers:
      - name: CHANGEME
        image: CHANGEME.azurecr.io/CHANGEME
        ports:
        - containerPort: CHANGEME
