apiVersion: apps/v1
kind: Deployment # A Kubernetes Deployment is used to tell Kubernetes how to create or modify instances of the pods that hold a containerized application
metadata:
  name: ratings-web-deployment
spec:   # A deployment's specification really only has a few useful options
  replicas: 1 # How many replicas do we want?
  selector: # Which pods are managed by this deployment?
    matchLabels: # This must match the labels we set on the pod!
      app: ratings-web
  template:   # This template field is a regular pod configuration nested inside the deployment spec
    metadata:
      labels:
        app: ratings-web # Set labels on the pod. This is used in the deployment selector.
    spec:
      containers:
      - name: ratings-web  # Just the name of your container. Is not referenced anywhere
        image: dmtyry.azurecr.io/ratings-web ## Where your image is located?
        ports:
        - containerPort: 80 ## Port that is open in your container (check dockerfile) 
